// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hplmldtcdyrcvkynqlul.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhwbG1sZHRjZHlyY3ZreW5xbHVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NTgxNjksImV4cCI6MjA2MzMzNDE2OX0.1705UnUaBE0PnsdZQlPFj9m-e95_J9shfweAmhum408";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);